### PR TITLE
fix: Remove org.json dependency

### LINKED ISSUE #196: Licensing issue with JSON-Java library
__Proposal:__

[JSON-Java dependency](https://github.com/stleary/JSON-java) does not have a free license. This can be exchanged by [Jackson](https://github.com/FasterXML/jackson).

__Current behavior:__

Currently `influxdb-client-core` depends on the [JSON-Java library](https://github.com/stleary/JSON-java).
image

__Desired behavior:__

JSON-Serialization function in [AbstractQueryApi](https://github.com/influxdata/influxdb-client-java/blob/02039edb7805e56b74b0a837c19eb4a1d6fcd705/client-core/src/main/java/com/influxdb/internal/AbstractQueryApi.java#L77) (client-core) can be exchanged with an alternative implementation using [Jackson](https://github.com/FasterXML/jackson)

__Alternatives considered:__

Jackson is the most commonly used (de)serialization library. No other alternative considered.

__Use case:__

Due to the [license terms](https://github.com/stleary/JSON-java/blob/master/LICENSE) of `json-java`, JSON License does not count as a free software license. The sentence in license terms "The Software shall be used for Good, not Evil." is relative for interpretation and bounding it's usage. This definition [does not fit](https://opensource.org/faq#evil) into free/open-source software definition.

### PR DESCRIPTION
**Pull request by rhajek**
Closes #196

## Proposed Changes

Remove badly licenced org.json library and relace it with gson.

## Checklist

- [x] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] A test has been added if appropriate
- [x] `mvn test` completes successfully
- [x] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: client-core/src/main/java/com/influxdb/exceptions/InfluxException.java [hunk 1]
```diff
@@ -118,22 +119,23 @@ public int status() {
      * @return a response body
      */
     @Nonnull
-    public JSONObject errorBody() {
+    public JsonObject errorBody() {
```
Comment (bednar) [inline client-core/src/main/java/com/influxdb/exceptions/InfluxException.java:122]: This is a breaking change for our public API. Will we change a major version of client?

What about use a generic map `Map<String, Object>` to avoid dependency to third party library?

File: client-core/src/main/java/com/influxdb/internal/AbstractQueryApi.java [hunk 2]
```diff
@@ -58,12 +60,9 @@
...
 
-    protected static final JSONObject DEFAULT_DIALECT = new JSONObject()
-            .put("header", true)
-            .put("delimiter", ",")
-            .put("quoteChar", "\"")
-            .put("commentPrefix", "#")
-            .put("annotations", new JSONArray().put("datatype").put("group").put("default"));
+    protected static final JsonObject DEFAULT_DIALECT = new JsonParser().parse("{\"header\":true,"
+        + "\"delimiter\":\",\",\"quoteChar\":\"\\\"\",\"commentPrefix\":\"#\","
+        + "\"annotations\":[\"datatype\",\"group\",\"default\"]}").getAsJsonObject();
```
Comment (bednar) [inline client-core/src/main/java/com/influxdb/internal/AbstractQueryApi.java:65]: We could initialise `DEFAULT_DIALECT` as a `String` to avoid unnecessary `toString()` in usages .

```suggestion
    protected static final String DEFAULT_DIALECT;
    static {
        Map<String, Object> dialect = new HashMap<>();
        dialect.put("header", true);
        dialect.put("delimiter", ",");
        dialect.put("quoteChar", "\"");
        dialect.put("commentPrefix", "#");
        dialect.put("annotations", new String[]{"datatype", "group", "default"});
        DEFAULT_DIALECT = new GsonBuilder().create().toJson(dialect);
    }
```

File: client-core/src/main/java/com/influxdb/exceptions/InfluxException.java (hunk 1 above)
Comment (rhajek) [reply client-core/src/main/java/com/influxdb/exceptions/InfluxException.java:122]: Yes, we should increase major version. Completely remove json from public api is better.

**Review by bednar — APPROVED** [review]
👍
