### PR TITLE
fix: mapping `Number` types to POJO query output

### LINKED ISSUE #410: Problem Mapping Long fields
When It is mapped a Long (Not primitive) field on model class and we use pivot function to return the values for each field on model, a Cast exception is thrown during the execution.

It says is not possible cast Long to Double.
When we use long (primitive) it doesn't throw error, however it returns zero (not behavior expected).

__Steps to reproduce__:

1. Create a model with 2 fields:

ModelInflux.java
```
//use lombok

@Getter
@Setter
@Measurement(name="model2")
@ToString
public class ModelInflux {

   @Column
  private Long field1;
  @Column
  private Double field2;

  @Column(timestamp = true, name = "time")
  private Instant timestamp;

}

```
2. Save some data on InfluxDB
Main.java
```
  public static void save(ModelInflux object, InfluxDBClientReactive client) {
    WriteReactiveApi writeApi = client.getWriteReactiveApi();

    var publisher = writeApi.writeMeasurement(WritePrecision.NS, object);
    Disposable subscriber =
        Flowable.fromPublisher(publisher)
            .subscribe(success -> log.info("Successfully written ModelInflux measurement"));
    subscriber.dispose();
  }
```

3. Create a query with pivot function:
```
private static void runModelInflux(String host, String org, String token, String bucket)
      throws InterruptedException {

    String query = "from(bucket: \"test2\")"
        + "  |> range(start: -1h, stop: now())"
        + "  |> filter(fn: (r) => r[\"_measurement\"] == \"model2\")"
        + "  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)"
        + "  |> yield(name: \"mean\")"
        + "  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")";

    InfluxDBClientReactive client = InfluxDBClientReactiveFactory
        .create(host, token.toCharArray(), org, bucket);

    ModelInflux modelInflux = new ModelInflux();
    modelInflux.setField1((long)(Math.random() * 100));
    modelInflux.setField2((Math.random() * 100));

    save(modelInflux, client);

    Thread.sleep(1000);

    Instant end = Instant.now();
    Instant start = Instant.now().minus(1, ChronoUnit.HOURS);

    execute(query, client).doOnEach( e -> {
      if (e.get() != null) {
        log.info(e.get().toString());
      }
    }).doOnError(e -> {
      log.error(e.getMessage());
    }).subscribe();

    // Giving a time to process the result.
    Thread.sleep(10000);
  }
```
Main.java

```
  public static void main(String[] args) throws InterruptedException {
    String host = Main.HOST;
    String org = Main.ORG;
    String token= Main.TOKEN;
    String bucket = Main.BUCKET;

    runModelInflux2(host, org, token, "test2");
  }
```

__Expected Behavior__:

Return the model without error and value available.

__Actual Behavior__:
Error:
Caused by: com.influxdb.exceptions.InfluxException: Can not set java.lang.Long field com.autonomic.test.domain.ModelInflux2.field1 to java.lang.Double

__Specifications:__
 - Client Version: 6.4.0
 - InfluxDB Version: 2.0.9
 - JDK Version: Corretto 11.0.15.9.1
 - Platform: Mac OS M1

PS.: I see this code is converting only to primitives. (Maybe include more options to conversion?)
https://github.com/influxdata/influxdb-client-java/blob/f9f6aa0429977525ffaef4f745ab1f7958623cb1/client-core/src/main/java/com/influxdb/query/internal/FluxResultMapper.java#L132-L144

### PR DESCRIPTION
**Pull request by bednar**
Closes #410

## Proposed Changes

Fixed mapping aggregated results (changed type) from InfluxDB.

## Checklist

- [x] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] A test has been added if appropriate
- [x] `mvn test` completes successfully
- [x] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

### CODE REVIEW

File: client-core/src/main/java/com/influxdb/query/internal/FluxResultMapper.java [hunk 1]
```diff
@@ -129,16 +129,16 @@ private void setFieldValue(@Nonnull final Object object,
...
+            if (long.class.isAssignableFrom(fieldType) || Long.class.isAssignableFrom(fieldType)) {
+                field.set(object, toLongValue(value));
                 return;
             }
-            if (int.class.isAssignableFrom(fieldType)) {
-                field.setInt(object, toIntValue(value));
+            if (int.class.isAssignableFrom(fieldType) || Integer.class.isAssignableFrom(fieldType)) {
+                field.set(object, toIntValue(value));
                 return;
             }
```
Comment (michaelahojna) [inline client-core/src/main/java/com/influxdb/query/internal/FluxResultMapper.java:143]:
```suggestion
            }
            if (short.class.isAssignableFrom(fieldType) || Short.class.isAssignableFrom(fieldType)) {
                field.set(object, toShortValue(value));
                return;
            }
            if (float.class.isAssignableFrom(fieldType) || Float.class.isAssignableFrom(fieldType)) {
                field.set(object, toFloatValue(value));
                return;
            }
```

File: client-core/src/main/java/com/influxdb/query/internal/FluxResultMapper.java [hunk 2]
```diff
@@ -190,7 +190,7 @@ private int toIntValue(final Object value) {
             return (int) value;
         }
 
-        return ((Double) value).intValue();
+        return ((Number) value).intValue();
     }
```
Comment (michaelahojna) [inline client-core/src/main/java/com/influxdb/query/internal/FluxResultMapper.java:195]:
```suggestion

 private short toShortValue(final Object value) {

        if (short.class.isAssignableFrom(value.getClass()) || Short.class.isAssignableFrom(value.getClass())) {
            return (short) value;
        }

        return ((Number) value).shortValue();
    }

    private float toFloatValue(final Object value) {

        if (float.class.isAssignableFrom(value.getClass()) || Float.class.isAssignableFrom(value.getClass())) {
            return (float) value;
        }

        return ((Number) value).floatValue();
    }
```

File: client-core/src/main/java/com/influxdb/query/internal/FluxResultMapper.java [hunk 3]
```diff
@@ -190,7 +190,7 @@ private int toIntValue(final Object value) {
...
 
     private BigDecimal toBigDecimalValue(final Object value) {
```
Comment (michaelahojna) [inline client-core/src/main/java/com/influxdb/query/internal/FluxResultMapper.java:196]:
```suggestion
    private BigDecimal toBigDecimalValue(final Object value) {
        if (float.class.isAssignableFrom(value.getClass()) || Float.class.isAssignableFrom(value.getClass())) {
            return BigDecimal.valueOf((float) value);
        }
        if (short.class.isAssignableFrom(value.getClass()) || Short.class.isAssignableFrom(value.getClass())) {
            return BigDecimal.valueOf((short) value);
        }
```

**Review by michaelahojna — CHANGES_REQUESTED** [review]
@bednar thanks for your PR, please add also mapping for short and float types.

**Review by michaelahojna — APPROVED** [review]
