### PR TITLE
fix: Issue/684

### LINKED ISSUE #684: Java client: SHOW SERIES return empty result
Hi,
During implementation of tool that needs to retrieve schema of InfluxDB 2.7, I have encountered issue where `show series` return empty result, although underlying CSV contains correct data.

Data retrieved underneath as CSV is in format (note that two columns are empty!):
```
name,tags,key
,,temperature
,,pressure
```

I believe issue is in line https://github.com/influxdata/influxdb-client-java/blob/master/client/src/main/java/com/influxdb/client/internal/InfluxQLQueryApiImpl.java#L129 where last line of CSV is detected incorrectly, and instead of

```java
if (csvRecord.size() == 1 || csvRecord.get(0).equals("")) {
```
it should be
```java
if (csvRecord.size() == 1 && csvRecord.get(0).equals("")) {
```

__Steps to reproduce:__

1. Run `InfluxQLQueryResult result = client.getInfluxQLQueryApi().query(new InfluxQLQuery("SHOW SERIES", "mydb"));`
2. Observe that `result.getResults().size() == 1`, but `result.getResults().get(0).getSeries().size() == 0`

__Expected behavior:__
Object `InfluxQLQueryResult` should contain list of series retrieved from InfluxDB, as running `SHOW SERIES` from command line does it.

__Actual behavior:__
Describe What actually happened.

__Specifications:__
 - Client Version: 7.0.0
 - InfluxDB Version: 2.7.0
 - JDK Version: openjdk version "17.0.8.1" 2023-08-24
 - Platform: Linux (Arch)

### PR DESCRIPTION
**Pull request by karel-rehor**
Closes #684

## Proposed Changes

Fixes logic in check of marker for end of table in CSV stream.  `InfluxQLQueryApiImpl:129`

## Checklist

- [x] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] A test has been added if appropriate
- [x] `mvn test` completes successfully
- [x] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

### CODE REVIEW

File: client/src/test/java/com/influxdb/client/internal/InfluxQLQueryApiImplTest.java [hunk 1]
```diff
@@ -70,12 +74,19 @@ void readInfluxQLResult() throws IOException {
...
 				"cpu,\"region=us-east-1,host=server1\",1483225201,14.06,1.7\n" +
-				"cpu,\"region=us-east-1,host=server2\",1483225200,67.91,1.3\n");
+				"cpu,\"region=us-east-1,host=server2\",1483225200,67.91,1.3\n" +
+			  "\n" +
+			  "name,tags,key\n" + //emulate SHOW SERIES response
+			  ",,temperature\n" +
+			  ",,\"pressure\"\n" +
+			  ",,humid\n" +
+			  ",,\"temperature,locale=nw002,device=rpi5_88e1\""
+			);
```
Comment (bednar) [inline client/src/test/java/com/influxdb/client/internal/InfluxQLQueryApiImplTest.java:84]: Please add this as new test, something like `testShowSeries`. It will be better for future maintenance of `InfluxQLQueryApiImplTest.java`.

**Review by bednar — CHANGES_REQUESTED** [review]

**Review by bednar — APPROVED** [review]
LGTM 🚀
